//ADC
#define ADC_ATTEN ADC_ATTEN_DB_0     //0 dB (100mV - 900mV)
#define ADC_WIDTH ADC_WIDTH_BIT_12

//buffer letture <analogiche runningmedia>   
#define DIM_BUFFER_VOLTAGE 12
#define DIM_BUFFER_CURRENT 12
#define DIM_BUFFER_EXT_VREF 12
#define DISCARDS_VOLTAGE_VALUE 2
#define DISCARDS_CURRENT_VALUE 2
#define DISCARDS_EXT_VREF_VALUE 2